# パラメータ定義
#parameters:
  # sample_payment.xxx: 1

# コンテナ定義
#services:

# スロットリングの定義
eccube:
  rate_limiter:
    sample_payment_mypage_card_info:
      route: sample_payment_mypage_card_info
      method: ['POST']
      type: ['ip', 'customer']
      limit: 5
      interval: '60 minutes'
